const Campground=require("../models/campground");
const Comment= require("../models/comment");
const middlewareObject={};
middlewareObject.isValidUser=(req,res,next)=>{
    if(req.isAuthenticated())
    {
        Campground.findById(req.params.id,(err,found)=>{
            if(err)
            res.redirect("back");
             else
            { 
                 if(found.author.id.equals(req.user._id))
                {
                    next();
                }
                else
                {
                  res.redirect("back")
                }
            }
    }
        );
    }
    else
    res.redirect("back");
}
middlewareObject.isValidUserComment=(req,res,next)=>{
    if(req.isAuthenticated())
    {
        Comment.findById(req.params.comment_id,(err,found)=>{
            if(err)
            res.redirect("back");
             else
            { 
                 if(found.author.id.equals(req.user._id))
                {
                    next();
                }
                else
                {
                  res.redirect("back")
                }
            }
    }
        );
    }
    else
    res.redirect("back");
}
middlewareObject.isLoggedIn=(req,res,next)=>{
    if(req.isAuthenticated()){
        return next();
    }
    res.redirect("/login")
}
module.exports=middlewareObject;